CREATE TABLE [dbo].[TB_SubViaje] (
    [subViajeIdS]                               INT             IDENTITY (1, 1) NOT NULL,
    [subViajeId]                                VARCHAR (50)    COLLATE Modern_Spanish_CI_AS NULL,
    [tripId]                                    VARCHAR (50)    COLLATE Modern_Spanish_CI_AS NOT NULL,
    [TripIdS]                                   INT             NOT NULL,
    [assetId]                                   VARCHAR (50)    COLLATE Modern_Spanish_CI_AS NOT NULL,
    [assetIdS]                                  INT             NOT NULL,
    [departSubTrip]                             DATETIME        NULL,
    [distanceKilometers]                        DECIMAL (11, 4) NULL,
    [driverId]                                  VARCHAR (50)    COLLATE Modern_Spanish_CI_AS NOT NULL,
    [driverIdS]                                 INT             NOT NULL,
    [drivingTime]                               DECIMAL (18, 4) NOT NULL,
    [duration]                                  DECIMAL (18, 4) NOT NULL,
    [endEngineSeconds]                          INT             NULL,
    [endOdometerKilometers]                     DECIMAL (11, 4) NULL,
    [endPositionId]                             VARCHAR (50)    COLLATE Modern_Spanish_CI_AS NULL,
    [endPositionIdS]                            INT             NULL,
    [engineSeconds]                             INT             NOT NULL,
    [estadoBase]                                BIT             NOT NULL,
    [fastHalt]                                  DATETIME        NULL,
    [firstDepart]                               DATETIME        NULL,
    [fuelUsedLitres]                            DECIMAL (11, 4) NULL,
    [grupoIdS]                                  INT             NOT NULL,
    [haltSubTrip]                               DATETIME        NULL,
    [maxAccelerationKilometersPerHourPerSecond] DECIMAL (18, 4) NOT NULL,
    [maxDecelerationKilometersPerHourPerSecond] DECIMAL (18, 4) NOT NULL,
    [maxRpm]                                    DECIMAL (18, 4) NOT NULL,
    [maxSpeedKilometersPerHour]                 DECIMAL (18, 4) NOT NULL,
    [pulseValueSubTrip]                         DECIMAL (16, 4) NULL,
    [standingTime]                              DECIMAL (18, 4) NOT NULL,
    [startEngineSeconds]                        DECIMAL (18, 4) NULL,
    [startOdometerKilometers]                   DECIMAL (11, 4) NULL,
    [startPositionId]                           VARCHAR (50)    COLLATE Modern_Spanish_CI_AS NULL,
    [startPositionIdS]                          INT             NULL,
    [subTripEnd]                                DATETIME        NULL,
    [subTripStart]                              DATETIME        NULL,
    [tripEnd]                                   DATETIME        NOT NULL,
    [tripStart]                                 DATETIME        NOT NULL,
    [FechaSistema]                              DATETIME        NULL,
    [CantSubViajes]                             INT             NULL,
    [ClienteIds]                                INT             NULL,
    CONSTRAINT [PK__TB_SubVi__2E9744AB91EB5796] PRIMARY KEY CLUSTERED ([subViajeIdS] ASC),
    UNIQUE NONCLUSTERED ([tripId] ASC, [subViajeId] ASC, [tripStart] ASC, [subTripStart] ASC)
);

