CREATE TABLE [dbo].[TB_TripsMetrics] (
    [TripsMetricsId]                            INT             IDENTITY (1, 1) NOT NULL,
    [MaxAccelerationKilometersPerHourPerSecond] DECIMAL (11, 4) NULL,
    [MaxSpeedKilometersPerHour]                 DECIMAL (11, 4) NULL,
    [ExcessiveIdleOccurs]                       INT             NULL,
    [HarshAccelerationOccurs]                   INT             NULL,
    [HarshBrakeOccurs]                          INT             NULL,
    [SpeedingOccurs]                            INT             NULL,
    [OutOfGreenBandTime]                        INT             NULL,
    [ExcessiveIdleTime]                         INT             NULL,
    [MaxDecelerationKilometersPerHourPerSecond] DECIMAL (11, 4) NULL,
    [OverRevTime]                               INT             NULL,
    [HarshBrakeTime]                            INT             NULL,
    [SpeedingTime]                              INT             NULL,
    [DistanceKilometers]                        DECIMAL (11, 4) NULL,
    [Duration]                                  DECIMAL (11, 4) NULL,
    [DrivingTime]                               DECIMAL (11, 4) NULL,
    [TripStart]                                 DATETIME        NULL,
    [DriverId]                                  BIGINT          NULL,
    [AssetId]                                   BIGINT          NULL,
    [TripId]                                    BIGINT          NULL,
    [HarshAccelerationTime]                     INT             NULL,
    [MaxRpm]                                    DECIMAL (11, 4) NULL,
    [FechaSistema]                              DATETIME        NOT NULL,
    [IdleOccurs]                                INT             NULL,
    [IdleTime]                                  INT             NULL,
    [ClienteIds]                                INT             NULL,
    PRIMARY KEY CLUSTERED ([TripsMetricsId] ASC),
    UNIQUE NONCLUSTERED ([TripId] ASC)
);

