CREATE TABLE [dbo].[TB_Usuarios] (
    [usuarioIdS]               INT              IDENTITY (1, 1) NOT NULL,
    [nombre]                   VARCHAR (100)    COLLATE Modern_Spanish_CI_AS NOT NULL,
    [apellido]                 VARCHAR (100)    COLLATE Modern_Spanish_CI_AS NOT NULL,
    [telefono]                 VARCHAR (20)     COLLATE Modern_Spanish_CI_AS NOT NULL,
    [documento]                VARCHAR (20)     COLLATE Modern_Spanish_CI_AS NOT NULL,
    [correo]                   VARCHAR (100)    COLLATE Modern_Spanish_CI_AS NOT NULL,
    [key]                      VARBINARY (MAX)  NOT NULL,
    [IV]                       VARBINARY (MAX)  NOT NULL,
    [usuario]                  VARCHAR (50)     COLLATE Modern_Spanish_CI_AS NOT NULL,
    [fechaCreacion]            DATETIME         NOT NULL,
    [fechaUltimaActualizacion] DATETIME         NOT NULL,
    [fechaUltimoIngreso]       DATETIME         NOT NULL,
    [perfilIdS]                INT              NOT NULL,
    [estadoUsuarioIdS]         INT              NOT NULL,
    [contrasena]               VARBINARY (MAX)  NOT NULL,
    [notificacion]             BIT              NULL,
    [imagen]                   VARBINARY (MAX)  NULL,
    [TokenRecuperacion]        UNIQUEIDENTIFIER NULL,
    [FechaExpiracion]          DATETIME         NULL,
    [Intentos]                 INT              NULL,
    CONSTRAINT [PK_TB_Usuarios] PRIMARY KEY CLUSTERED ([usuarioIdS] ASC),
    CONSTRAINT [FK_TB_Usuarios_TB_Perfil] FOREIGN KEY ([perfilIdS]) REFERENCES [dbo].[TB_Perfil] ([perfilIdS])
);

