CREATE TABLE [dbo].[TB_ViajeTemp] (
    [Id]                      INT             IDENTITY (1, 1) NOT NULL,
    [TripId]                  BIGINT          NOT NULL,
    [SubViajeId]              BIGINT          NULL,
    [AssetId]                 INT             NULL,
    [RegistrationNumber]      VARCHAR (50)    NOT NULL,
    [DistanceKilometers]      DECIMAL (18, 4) NOT NULL,
    [DrivingTime]             INT             NOT NULL,
    [Duration]                INT             NOT NULL,
    [FuelUsedLitres]          DECIMAL (18, 4) NULL,
    [StandingTime]            DECIMAL (18, 4) NOT NULL,
    [StartOdometerKilometers] DECIMAL (18, 4) NOT NULL,
    [EndOdometerKilometers]   DECIMAL (18, 4) NOT NULL,
    [TripStart]               DATETIME        NULL,
    [StartLatitud]            FLOAT (53)      NULL,
    [StartLongitud]           FLOAT (53)      NULL,
    [StartFormatteAddress]    VARCHAR (250)   NULL,
    [TripEnd]                 DATETIME        NULL,
    [EndLatitud]              FLOAT (53)      NULL,
    [EndLongitud]             FLOAT (53)      NULL,
    [EndFormatteAddress]      VARCHAR (250)   NULL,
    [FechaSistema]            DATETIME        NULL,
    [CantSubViajes]           INT             NULL,
    CONSTRAINT [PK_TB_ViajeTemp] PRIMARY KEY CLUSTERED ([Id] ASC)
);

