
-- =============================================
-- Author:		ygonzalez
-- Create date: 27/04/2021
-- Description:	Inserta valores de imga
-- =============================================
create PROCEDURE dbo.SP_InsertaDatosIMG
(
@Data [UDT_ErroresViajeUsos] READONLY
)
AS
BEGIN

INSERT INTO [dbo].[TB_ErroresViajesyUso]
           ([Cliente]
           ,[US]
           ,[VehicleID]
           ,[Placa]
           ,[VehicleSiteID]
           ,[VehicleSiteName]
           ,[TripNo]
           ,[DriverID]
           ,[DriverName]
           ,[DriverSiteID]
           ,[DriverSiteName]
           ,[OriginalDriverID]
           ,[OriginalDriverName]
           ,[TripStart]
           ,[TripEnd]
           ,[CategoryID]
           ,[Notes]
           ,[StartSubTripSeq]
           ,[EndSubTripSeq]
           ,[TripDistance]
           ,[Odometer]
           ,[MaxSpeed]
           ,[SpeedTime]
           ,[SpeedOccurs]
           ,[MaxBrake]
           ,[BrakeTime]
           ,[BrakeOccurs]
           ,[MaxAccel]
           ,[AccelTime]
           ,[AccelOccurs]
           ,[MaxRPM]
           ,[RPMTime]
           ,[RPMOccurs]
           ,[GBTime]
           ,[ExIdleTime]
           ,[ExIdleOccurs]
           ,[NIdleTime]
           ,[NIdleOccurs]
           ,[StandingTime]
           ,[Litres]
           ,[StartGPSID]
           ,[EndGPSID]
           ,[StartEngineSeconds]
           ,[EndEngineSeconds]
           ,[ClienteIdS])
  
select [Cliente]
           ,[US]
           ,[VehicleID]
           ,[Placa]
           ,[VehicleSiteID]
           ,[VehicleSiteName]
           ,[TripNo]
           ,[DriverID]
           ,[DriverName]
           ,[DriverSiteID]
           ,[DriverSiteName]
           ,[OriginalDriverID]
           ,[OriginalDriverName]
           ,[TripStart]
           ,[TripEnd]
           ,[CategoryID]
           ,[Notes]
           ,[StartSubTripSeq]
           ,[EndSubTripSeq]
           ,[TripDistance]
           ,[Odometer]
           ,[MaxSpeed]
           ,[SpeedTime]
           ,[SpeedOccurs]
           ,[MaxBrake]
           ,[BrakeTime]
           ,[BrakeOccurs]
           ,[MaxAccel]
           ,[AccelTime]
           ,[AccelOccurs]
           ,[MaxRPM]
           ,[RPMTime]
           ,[RPMOccurs]
           ,[GBTime]
           ,[ExIdleTime]
           ,[ExIdleOccurs]
           ,[NIdleTime]
           ,[NIdleOccurs]
           ,[StandingTime]
           ,[Litres]
           ,[StartGPSID]
           ,[EndGPSID]
           ,[StartEngineSeconds]
           ,[EndEngineSeconds]
           ,[ClienteIdS]
		   from @Data


END