CREATE TYPE [dbo].[UDT_EventType] AS TABLE (
    [EventId]            BIGINT       NOT NULL,
    [DriverId]           BIGINT       NULL,
    [AssetId]            BIGINT       NULL,
    [EventDateTime]      DATETIME     NOT NULL,
    [ReceivedDateTime]   DATETIME     NULL,
    [EventTypeId]        BIGINT       NULL,
    [OdometerKilometres] DECIMAL (18) NULL,
    [ValueUnits]         VARCHAR (30) NULL,
    [ValueType]          VARCHAR (30) NULL,
    [ValueEvent]         DECIMAL (18) NULL,
    [SpeedLimit]         DECIMAL (18) NULL,
    [PositionId]         BIGINT       NULL,
    [PriorityEvent]      INT          NULL,
    [Armed]              BIT          NULL,
    [assetIdS]           INT          NULL,
    [driverIdS]          INT          NULL,
    [eventTypeIdS]       INT          NULL,
    [TotalOccurances]    INT          NULL,
    [TotalTimeSeconds]   INT          NULL,
    PRIMARY KEY CLUSTERED ([EventId] ASC));

