CREATE TYPE [dbo].[UDT_TripsMetrics] AS TABLE (
    [TripId]                                    BIGINT          NOT NULL,
    [MaxAccelerationKilometersPerHourPerSecond] DECIMAL (18, 2) NOT NULL,
    [MaxSpeedKilometersPerHour]                 DECIMAL (18, 2) NOT NULL,
    [ExcessiveIdleOccurs]                       INT             NULL,
    [HarshAccelerationOccurs]                   INT             NULL,
    [HarshBrakeOccurs]                          INT             NULL,
    [SpeedingOccurs]                            INT             NULL,
    [OutOfGreenBandTime]                        INT             NULL,
    [ExcessiveIdleTime]                         INT             NULL,
    [MaxDecelerationKilometersPerHourPerSecond] DECIMAL (18, 2) NULL,
    [OverRevTime]                               INT             NULL,
    [HarshBrakeTime]                            INT             NULL,
    [SpeedingTime]                              INT             NULL,
    [DistanceKilometers]                        DECIMAL (18, 2) NULL,
    [Duration]                                  DECIMAL (18, 2) NULL,
    [DrivingTime]                               DECIMAL (18, 2) NULL,
    [TripStart]                                 DATETIME        NULL,
    [DriverId]                                  BIGINT          NULL,
    [AssetId]                                   BIGINT          NULL,
    [HarshAccelerationTime]                     INT             NULL,
    [MaxRpm]                                    INT             NULL,
    [FechaSistema]                              DATETIME        NOT NULL,
    [IdleOccurs]                                INT             NULL,
    [IdleTime]                                  INT             NULL,
    PRIMARY KEY CLUSTERED ([TripId] ASC));

