CREATE TYPE [dbo].[UDT_Positions] AS TABLE (
    [PositionId]                     BIGINT          NOT NULL,
    [AgeOfReadingSeconds]            INT             NULL,
    [AltitudeMetres]                 INT             NULL,
    [AssetId]                        VARCHAR (50)    NULL,
    [DistanceSinceReadingKilometres] DECIMAL (16, 4) NULL,
    [DriverId]                       VARCHAR (50)    NULL,
    [FormattedAddress]               VARCHAR (50)    NULL,
    [Hdop]                           BIT             NULL,
    [Heading]                        DECIMAL (16, 4) NULL,
    [IsAvl]                          BIT             NULL,
    [Latitude]                       DECIMAL (16, 4) NULL,
    [Longitude]                      DECIMAL (16, 4) NULL,
    [NumberOfSatellites]             INT             NULL,
    [OdometerKilometres]             DECIMAL (16, 4) NULL,
    [Pdop]                           BIT             NULL,
    [SpeedKilometresPerHour]         DECIMAL (16, 4) NULL,
    [SpeedLimit]                     DECIMAL (16, 4) NULL,
    [Timestamp]                      DATETIME        NULL,
    [Vdop]                           BIT             NULL,
    [assetPositionId]                VARCHAR (50)    NULL,
    [estadoBase]                     BIT             NULL,
    [fechaSistema]                   DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([PositionId] ASC));

