CREATE TABLE [FIDELIZACION].[DetalleAld] (
    [DetalleAldId]       INT           IDENTITY (1, 1) NOT NULL,
    [Dispositivo]        VARCHAR (250) NULL,
    [Cedula]             VARCHAR (250) NOT NULL,
    [Nombre]             VARCHAR (250) NULL,
    [Nombre2]            VARCHAR (250) NULL,
    [Apellido]           VARCHAR (250) NULL,
    [Apellido2]          VARCHAR (250) NULL,
    [Gerencias]          VARCHAR (250) NOT NULL,
    [Cargo]              VARCHAR (250) NULL,
    [Aceleraciones]      INT           NULL,
    [Frenados]           INT           NULL,
    [EVelocidad]         INT           NULL,
    [Ralenti]            INT           NULL,
    [TotalEventos]       INT           NULL,
    [TiempoEV]           DECIMAL (18)  NULL,
    [DrivingScore]       DECIMAL (18)  NULL,
    [DistanciaRecorrida] DECIMAL (18)  NULL,
    [EsActivo]           BIT           CONSTRAINT [DF_DetalleAld_EsActivo] DEFAULT ((1)) NOT NULL,
    [AldId]              INT           NOT NULL,
    [FechaFinal]         DATETIME      NOT NULL,
    [FechaSistema]       DATETIME      NOT NULL,
    CONSTRAINT [PK_DetalleAld] PRIMARY KEY CLUSTERED ([DetalleAldId] ASC),
    CONSTRAINT [FK_DetalleAld_Ald] FOREIGN KEY ([AldId]) REFERENCES [FIDELIZACION].[Ald] ([AldId])
);

